name: Build & Release

on:
  push:
    tags: [ 'v*.*.*' ]  # v1.0.0 などタグを push するとリリース

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build jar
        run: ./gradlew jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: burp-highlighter-jar
          path: build/libs/*.jar
          retention-days: 7

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: burp-highlighter-jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.jar"
