name: Build & Release Burp Extension

on:
  push:
    branches: [ main ]
    tags:     [ 'v*.*.*' ]      # バージョンタグを切った時はリリースも自動化
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build fat‑jar
        run: ./gradlew shadowJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: burp-duplicate-highlighter
          path: build/libs/*-all.jar
          retention-days: 30

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: burp-duplicate-highlighter

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.jar"
          draft: false
          prerelease: false
